apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml

namespace: lume-site

commonLabels:
  app.kubernetes.io/name: lume-site
  app.kubernetes.io/part-of: lume-site