apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lume-site.fullname" . }}-nginx-config
  labels:
    {{- include "lume-site.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Values.nginx.config | indent 4 }}